#ifndef _LWIPOPTS_H
#define _LWIPOPTS_H

// Claude helpfully suggested these settings
#define LWIP_FREERTOS_SYS_ARCH 1
#define TCPIP_THREAD_STACKSIZE 4096
#define DEFAULT_THREAD_STACKSIZE 2048
#define DEFAULT_RAW_RECVMBOX_SIZE 8
#define TCPIP_MBOX_SIZE 8
#define DEFAULT_UDP_RECVMBOX_SIZE 8
#define DEFAULT_TCP_RECVMBOX_SIZE 8
#define DEFAULT_ACCEPTMBOX_SIZE 8

#define LWIP_DEBUG
#define LWIP_TIMEVAL_PRIVATE 0

#define PBUF_POOL_SIZE 16
#define PBUF_POOL_BUFSIZE 1536

#endif